# Setup
title:        Abdul Rahman K - Blogs
tagline:      Single source of truth of all my blogs (From Medium,LinkedIn,etc)
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Abdul Rahman K
  url:        https://abdulrahmank.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown