# Setup
title:        Abdul Rahman K - Blogs
tagline:      Single source for all my blogs (From Medium,LinkedIn,etc)
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Abdul Rahman K
  url:        https://abdulrahmank.github.io/about

# Gems
gems:
  - jekyll-paginate

plugins:
  - jekyll-seo-tag

#Others
markdown: kramdown

# Blogs
post_topics:
  - name: Architecture
    posts:
      - date: Yet to publish
        url: #
        title: Amazon ECS quick brief
      - date: Yet to publish
        url: #
        title: How we migrated 190 million records from postgres to Dynamodb and Why?
      - date: Yet to publish
        url: /main/2020/03/24/creating-bff-using-krakend.html
        title: Creating a BFF(backend-for-frontend) using KrakenD

  - name: Programming
    posts:
      - date: May 26, 2020
        url: /main/2020/03/26/static-methods-in-ruby.html
        title: Static methods in ruby, explained
      - date: Yet to publish
        url: /main/2020/03/24/includes-vs-eager-loading-copy.html
        title: "ActiveRecord: includes, eager_load -- when not to use"
      - date: May 22, 2020
        url: https://medium.com/swlh/understanding-ruby-eigen-class-as-a-java-developer-1dd20d3cd725
        title: Understanding Ruby Eigen class as a Java Developer

  - name: Devops
    posts:
      - date: Sep 28, 2019
        url: https://medium.com/@kadkab.abdul/simplify-getting-started-978cfeece8d
        title: Simplify “Getting started” using docker
      - date: Sep 23, 2019
        url: https://medium.com/@kadkab.abdul/unblocking-development-using-nginx-29b729301848
        title: Unblocking development using Nginx
      - date: Jul 17, 2018
        url: https://medium.com/@kadkab.abdul/ansible-for-beginners-2cf3b27abe3b
        title: Ansible for Beginners

  - name: Mobile development
    posts:
      - date: Yet to publish
        url: #
        title: TDD in Flutter
      - date: Yet to publish
        url: #
        title: TDD in Android, using MVP
      - date: Yet to publish
        url: #
        title: Undertanding iOS development as an Android developer
      - date: Yet to publish
        url: #
        title: TDD in iOS, using MVVM
      - date: May 28, 2018
        url: https://android.jlelse.eu/know-about-android-code-that-is-solid-part-ii-7e41989f83b3
        title: Android O — SOLID
      - date: May 3, 2018
        url: https://android.jlelse.eu/android-s-srp-535402251c1b
        title: Android S — SOLID

projects:
  - name: Retail Biddah
    phase: In development
    url: /
    description: A POS solution that aims to reduce the waiting time in queues in super market.
  - name: Glad tidel
    phase: Ideation
    url: /
    description: A mobile app to notify users about the upcoming/ongoing prayer in the masjid that is near the user.