# Setup
title:        Abdul Rahman K - Blogs
tagline:      Single source for all my blogs (From Medium,LinkedIn,etc)
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Abdul Rahman K
  url:        https://github.com/abdulrahmank

# Gems
gems:
  - jekyll-paginate

plugins:
  - jekyll-seo-tag

#Others
markdown: kramdown

# Blogs
post_topics:
  - name: Architecture
    posts:
      - date: June 14, 2020
        url: /main/2020/06/14/amazon-ecs-quick-brief.html
        title: Amazon ECS quick brief
      - date: Yet to publish
        url: #
        title: How we migrated 190 million records from postgres to Dynamodb and Why?
      - date: Yet to publish
        url: #
        title: Creating a BFF(backend-for-frontend) using KrakenD

  - name: Programming
    posts:
      - date: May 26, 2020
        url: /main/2020/03/26/static-methods-in-ruby.html
        title: Static methods in ruby, explained
      - date: Yet to publish
        url: /main/2020/03/24/includes-vs-eager-loading-copy.html
        title: "ActiveRecord: includes, eager_load -- when not to use"
      - date: May 22, 2020
        url: https://medium.com/swlh/understanding-ruby-eigen-class-as-a-java-developer-1dd20d3cd725
        title: Understanding Ruby Eigen class as a Java Developer
      - date: Jul 05, 2022
        url: /main/2022-07-05-dry-it-out.html
        title: DRY it out!

  - name: Devops
    posts:
      - date: Sep 28, 2019
        url: https://medium.com/@kadkab.abdul/simplify-getting-started-978cfeece8d
        title: Simplify “Getting started” using docker
      - date: Sep 23, 2019
        url: https://medium.com/@kadkab.abdul/unblocking-development-using-nginx-29b729301848
        title: Unblocking development using Nginx
      - date: Jul 17, 2018
        url: https://medium.com/@kadkab.abdul/ansible-for-beginners-2cf3b27abe3b
        title: Ansible for Beginners

  - name: Mobile development
    posts:
      - date: May 28, 2018
        url: https://android.jlelse.eu/know-about-android-code-that-is-solid-part-ii-7e41989f83b3
        title: Android O — SOLID
      - date: May 3, 2018
        url: https://android.jlelse.eu/android-s-srp-535402251c1b
        title: Android S — SOLID
      - date: Nov 12, 2022
        url: main/2022-11-12-flutter-clean-architecture.html
        title: Flutter clean architecture

  - name: Software development
    posts:
      - date: June 14, 2020
        url: /main/2020/06/14/being-a-well-balanced-developer.html
        title: Being a well balanced developer - part 1. Embrace Questioning.
      - date: June 22, 2020
        url: /main/2020/06/22/productionalising-the-code.html
        title: Being a well balanced developer - part 2. Embrace Devops.
      - date: June 30, 2022
        url: /main/2022-06-30-fix-the-cause-dont-plaster-the-code.html
        title: Don't plaster the code, fix the cause
      - date: Aug 03, 2022
        url: /main/2022-08-08-how-i-brought-prod-down.html
        title: How I brought donw the prod environment

projects:
  - name: Retail Biddah
    phase: Productionalised and In development
    url: /main/2020/10/10/retail-biddah.html
    description: POS solution that brings ease of billing and better user experience to reduce customer waiting time in queue. Aims to achieve this by simple UI and easy to use with less learning curve.